### ISSUE TITLE
Make seting up easier

### ISSUE THREAD

**Issue by karlicoss** [karlicoss/HPI#1]
original issue: https://github.com/karlicoss/kobuddy/issues/1#issuecomment-542265994 and comment by @ashfaqfarooqui

**Comment by karlicoss** [comment]
I guess I'm not very keen on using submodules because I'm keen on keeping infrastructure as flexible as possible (so it would be easy to plug in different things).

However, perhaps `pip3 install --user -e .` would actually work well since it sort of symlinks package into site-packages. So you get convenience of having `my` package without a wrapper and easy hacking/editing of its source files for your own needs.

Could fefinitely work for `my` package since it's got not private data anyway. There is a slight security concern for exposing `my_configuration` though: potentially exposing it to other python packages through default pythonpath.

Also, `kobuddy` is a proper PIP package already (just not uploaded) on pypi so it's possible to install it through `pip3 install --user .` already. Perhaps `my` package could exploit this somehow.

**Comment by karlicoss** [comment]
Regarding json config: ideally I'd prefer `py` file because it's friendlier to python tooling (e.g IDE), generally more flexible and nicer to hack. Could still add some json compatibility mode I guess.

**Comment by sanzoghenzo** [comment]
Hi @karlicoss, I've fount this and the other project of yours and I'm glad someone did things for me already (I'm a very lazy programmer after all) ;)

I still have to try your ecosystem, but from what I've learned from the documentation and looking at the source code, I would like to share my thoughts:

- I like the Idea to make this, and every other repos in the ecosystem, a real python package that can act as libraries, so there will be no need to import a `my_cfg` module just to get the module from a custom path;
- the dependencies of the various `my` modules can be made an optional  using `extras_require` as you did with `testing`; for example if one wants to use only the Facebook exporter path, *he could `pip install hpi[fb]` to install `fbmessengerexport` - (unfortunately?) those dependencies needs to be proper python packages published to pypi, no git repositories are allowed;
- as you've already said, If someone wants to tinker with the source, the usual `pip install -e .` applies;
- I would avoid using py files for configuration (mainly for security issues and to be a bit more user "friendly"), I would rather read JSON/YAML/INI/TOML files with sane defaults fallback. A good library that maps config files to python classes is [file-config](https://github.com/stephen-bunn/file-config);
- my first choice for the config location would be a user directory like `~/.config/my` (that is also [dotfiles](https://dotfiles.github.io/) friendly) since it's unlikely that an user will run multiple instances of the tool with different configs (well, maybe one can have multiple accounts, but that can be handled with a well thought structure by a single instance)

Let me know what you think, I could help you in the process.

**Comment by karlicoss** [comment]
Hi, thanks for your comment! Seems that the topics of configuratio and modules overlap, so I guess, let's just continue discussing in https://github.com/karlicoss/HPI/issues/12

**Comment by karlicoss** [comment]
I guess I'm closing this since many things changed since -- docs, simpler configs, `hpi` CLI tool for creating configs.
