### ISSUE TITLE
my.media.youtube returning []

### ISSUE THREAD

**Issue by mdroidian** [karlicoss/HPI#113]
So I've set up HPI on Windows WSL2 Ubuntu 20.04.
But for the life of me I can't seem to get my.media.youtube to work

`python3 -c 'import my.media.youtube as yt; print(yt.watched())'`
Just returns `[]`

Also:
`python3 -c 'import my.media.youtube as yt; print(yt.stats())'`
`{'watched': {'count': 0, 'warning': 'THE ITERABLE RETURNED NO DATA'}}`

`python3 -c 'import my.google.takeout.paths as tk; print(tk.get_last_takeout())'` does return the takeout zip file.
And that file does have \Takeout\My Activity\YouTube\My Activity.html

`hpi doctor my.google.takeout.paths`
Comes back all green

but
`hpi modules --all` lists `[disabled: marked explicitly (via __NOT_HPI_MODULE__)]` for `my.google.takeout.paths`

I'm not sure where to go from here!
Any ideas what I could try next? 😎

**Comment by karlicoss** [comment]
Thanks for the details!

> python3 -c 'import my.media.youtube as yt; print(yt.stats())
just fyi, this would be the same as `hpi doctor my.media.youtube` 

> `[disabled: marked explicitly (via __NOT_HPI_MODULE__)`
yeah, that's expected, since `my.google.takeout.paths` is an auxiliary module, not the 'user-facing one'

Regarding the actual problem: hmm. My hunch would be that maybe there is some issue with the path within the zip archive on Windows?  i.e this bit https://github.com/karlicoss/HPI/blob/8abe66526dddf7307f2b68e28517d5531801b8a4/my/media/youtube.py#L21-L25 Although judging by Zipfile code it just always uses forward slashes internally, so should be portable.. https://github.com/python/cpython/blob/a4e7d5f750e06e31a80a83c2af02b1a40cecd0ff/Lib/zipfile.py#L355-L356

Can you put a breakpoint there, or a `print(last)` statement on line  to see if it actually finds the file there? 
Or maybe just `python3 -c "import my.google.takeout.paths as P; print(P.get_last_takeout(path='Takeout/My Activity/YouTube/MyActivity.html'))"` should work too

**Comment by mdroidian** [comment]
Yup, those returned `None`
But I figured it out!  The filepath in my takeout the file is `My Activity.html` but in ln21 of youtube.py it's `MyActivity.html`

Bleh, can't believe I missed that! 🙈

**Comment by karlicoss** [comment]
oh wow.. I checked mine and it's definitely `MyActivity.html`. Damnit :) 
I guess the easiest 'proper' fix would be to add another `get_last_takeout` call under that if condition, with `My Activity.html` to give it a chance to find a different file.
Somewhat related to https://github.com/karlicoss/HPI/issues/20, if there was a nice uniform interface, would be possible to use something like `glob('*Activity.html')`...

**Comment by karlicoss** [comment]
Btw, this is fixed in [seanbreckenridge/google_takeout_parser](https://github.com/seanbreckenridge/google_takeout_parse)

https://github.com/seanbreckenridge/google_takeout_parser/blob/546d1426f799f140b13ca27d4c9b63da62df3ac7/google_takeout_parser/path_dispatch.py#L116

So hopefully once we switch HPI to use it, we can close the issue!
